steps:
# Build the container image
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/devs-sandbox/ruby-slackbot
  - --cache=true
  # - --cache-ttl=48h # default 2 weeks
# Push the container image to Container Registry
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'ruby-slackbot', '--image', 'gcr.io/devs-sandbox/ruby-slackbot', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/devs-sandbox/ruby-slackbot
