steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/image
  - --cache=true
  - --cache-ttl=48h # default 2 weeks
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'ruby-slackbot', '--image', 'gcr.io/$PROJECT_ID/image', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
