version: '3'
services:
  ruby-slackbot:
    build: .
    ports:
    - 3000
    environment:
    - PORT=3000
    depends_on:
    - yaichi
  yaichi:
    image: mtsmfm/yaichi:1.7.0
    ports:
      - 80:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
